import { Component, ViewChild } from '@angular/core';
import { CountriesData, ChartSelectEvent, CountriesMapComponent  } from 'countries-map';
import { TemperatureForCountryService } from 'src/services/temperature-for-country.service';
import { FormControl } from '@angular/forms';
import { tap } from 'rxjs';

@Component({
  selector: 'app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.css']
})
export class MapComponent{
	actual_country: (string | number)[][] = []
	
	@ViewChild('map') map!: CountriesMapComponent
	constructor(private temperatureService: TemperatureForCountryService){}

	public select(event: ChartSelectEvent){
		console.log(event)
		let countryName = Object(this.countryListAlpha2)[event.country]
		if (Number.isNaN(this.mapData[event.country]["value"])){
			this.temperatureService.getTemperatures(this.actual_date, countryName).pipe(
				tap(data => {
					this.actual_country.push([countryName, Math.round(Object(data)[countryName])])
					this.mapData[event.country] = { "value": Math.round(Object(data)[countryName]) }
			})
			).subscribe()
		}
		else{
			let isInArray = false;
			for (let country of this.actual_country){
				if (country[0] == countryName){
					isInArray = true
					break
				}
			}
			if(!isInArray){
				this.actual_country.push([countryName, this.mapData[event.country]["value"]])
			}
		}
	}

	removeElementFromActualCountry(country_name:any){
		let i = 0;
		for (let country of this.actual_country){
			if (country[0] == country_name){
				this.actual_country.splice(i, 1)
				break
			}
			i++;
		}
	}

	actual_date: string | null = "2013-10-01"

	updateDate(){
		if(this.date != null){
			this.actual_date = this.date.value
		}
	}

	date = new FormControl('2013-10-01');

	public mapData: CountriesData = {
		"AF": {"value": NaN},
		"AL": {"value": NaN},
		"DZ": {"value": NaN},
		"AS": {"value": NaN},
		"AD": {"value": NaN},
		"AO": {"value": NaN},
		"AI": {"value": NaN},
		"AQ": {"value": NaN},
		"AG": {"value": NaN},
		"AR": {"value": NaN},
		"AM": {"value": NaN},
		"AW": {"value": NaN},
		"AU": {"value": NaN},
		"AT": {"value": NaN},
		"AZ": {"value": NaN},
		"BS": {"value": NaN},
		"BH": {"value": NaN},
		"BD": {"value": NaN},
		"BB": {"value": NaN},
		"BY": {"value": NaN},
		"BE": {"value": NaN},
		"BZ": {"value": NaN},
		"BJ": {"value": NaN},
		"BM": {"value": NaN},
		"BT": {"value": NaN},
		"BO": {"value": NaN},
		"BQ": {"value": NaN},
		"BA": {"value": NaN},
		"BW": {"value": NaN},
		"BV": {"value": NaN},
		"BR": {"value": NaN},
		"IO": {"value": NaN},
		"BN": {"value": NaN},
		"BG": {"value": NaN},
		"BF": {"value": NaN},
		"BI": {"value": NaN},
		"CV": {"value": NaN},
		"KH": {"value": NaN},
		"CM": {"value": NaN},
		"CA": {"value": NaN},
		"KY": {"value": NaN},
		"CF": {"value": NaN},
		"TD": {"value": NaN},
		"CL": {"value": NaN},
		"CN": {"value": NaN},
		"CX": {"value": NaN},
		"CC": {"value": NaN},
		"CO": {"value": NaN},
		"KM": {"value": NaN},
		"CD": {"value": NaN},
		"CG": {"value": NaN},
		"CK": {"value": NaN},
		"CR": {"value": NaN},
		"HR": {"value": NaN},
		"CU": {"value": NaN},
		"CW": {"value": NaN},
		"CY": {"value": NaN},
		"CZ": {"value": NaN},
		"CI": {"value": NaN},
		"DK": {"value": NaN},
		"DJ": {"value": NaN},
		"DM": {"value": NaN},
		"DO": {"value": NaN},
		"EC": {"value": NaN},
		"EG": {"value": NaN},
		"SV": {"value": NaN},
		"GQ": {"value": NaN},
		"ER": {"value": NaN},
		"EE": {"value": NaN},
		"SZ": {"value": NaN},
		"ET": {"value": NaN},
		"FK": {"value": NaN},
		"FO": {"value": NaN},
		"FJ": {"value": NaN},
		"FI": {"value": NaN},
		"FR": {"value": NaN},
		"GF": {"value": NaN},
		"PF": {"value": NaN},
		"TF": {"value": NaN},
		"GA": {"value": NaN},
		"GM": {"value": NaN},
		"GE": {"value": NaN},
		"DE": {"value": NaN},
		"GH": {"value": NaN},
		"GI": {"value": NaN},
		"GR": {"value": NaN},
		"GL": {"value": NaN},
		"GD": {"value": NaN},
		"GP": {"value": NaN},
		"GU": {"value": NaN},
		"GT": {"value": NaN},
		"GG": {"value": NaN},
		"GN": {"value": NaN},
		"GW": {"value": NaN},
		"GY": {"value": NaN},
		"HT": {"value": NaN},
		"HM": {"value": NaN},
		"VA": {"value": NaN},
		"HN": {"value": NaN},
		"HK": {"value": NaN},
		"HU": {"value": NaN},
		"IS": {"value": NaN},
		"IN": {"value": NaN},
		"ID": {"value": NaN},
		"IR": {"value": NaN},
		"IQ": {"value": NaN},
		"IE": {"value": NaN},
		"IM": {"value": NaN},
		"IL": {"value": NaN},
		"IT": {"value": NaN},
		"JM": {"value": NaN},
		"JP": {"value": NaN},
		"JE": {"value": NaN},
		"JO": {"value": NaN},
		"KZ": {"value": NaN},
		"KE": {"value": NaN},
		"KI": {"value": NaN},
		"KP": {"value": NaN},
		"KR": {"value": NaN},
		"KW": {"value": NaN},
		"KG": {"value": NaN},
		"LA": {"value": NaN},
		"LV": {"value": NaN},
		"LB": {"value": NaN},
		"LS": {"value": NaN},
		"LR": {"value": NaN},
		"LY": {"value": NaN},
		"LI": {"value": NaN},
		"LT": {"value": NaN},
		"LU": {"value": NaN},
		"MO": {"value": NaN},
		"MG": {"value": NaN},
		"MW": {"value": NaN},
		"MY": {"value": NaN},
		"MV": {"value": NaN},
		"ML": {"value": NaN},
		"MT": {"value": NaN},
		"MH": {"value": NaN},
		"MQ": {"value": NaN},
		"MR": {"value": NaN},
		"MU": {"value": NaN},
		"YT": {"value": NaN},
		"MX": {"value": NaN},
		"FM": {"value": NaN},
		"MD": {"value": NaN},
		"MC": {"value": NaN},
		"MN": {"value": NaN},
		"ME": {"value": NaN},
		"MS": {"value": NaN},
		"MA": {"value": NaN},
		"MZ": {"value": NaN},
		"MM": {"value": NaN},
		"NA": {"value": NaN},
		"NR": {"value": NaN},
		"NP": {"value": NaN},
		"NL": {"value": NaN},
		"NC": {"value": NaN},
		"NZ": {"value": NaN},
		"NI": {"value": NaN},
		"NE": {"value": NaN},
		"NG": {"value": NaN},
		"NU": {"value": NaN},
		"NF": {"value": NaN},
		"MP": {"value": NaN},
		"NO": {"value": NaN},
		"OM": {"value": NaN},
		"PK": {"value": NaN},
		"PW": {"value": NaN},
		"PS": {"value": NaN},
		"PA": {"value": NaN},
		"PG": {"value": NaN},
		"PY": {"value": NaN},
		"PE": {"value": NaN},
		"PH": {"value": NaN},
		"PN": {"value": NaN},
		"PL": {"value": NaN},
		"PT": {"value": NaN},
		"PR": {"value": NaN},
		"QA": {"value": NaN},
		"MK": {"value": NaN},
		"RO": {"value": NaN},
		"RU": {"value": NaN},
		"RW": {"value": NaN},
		"RE": {"value": NaN},
		"BL": {"value": NaN},
		"SH": {"value": NaN},
		"KN": {"value": NaN},
		"LC": {"value": NaN},
		"MF": {"value": NaN},
		"PM": {"value": NaN},
		"VC": {"value": NaN},
		"WS": {"value": NaN},
		"SM": {"value": NaN},
		"ST": {"value": NaN},
		"SA": {"value": NaN},
		"SN": {"value": NaN},
		"RS": {"value": NaN},
		"SC": {"value": NaN},
		"SL": {"value": NaN},
		"SG": {"value": NaN},
		"SX": {"value": NaN},
		"SK": {"value": NaN},
		"SI": {"value": NaN},
		"SB": {"value": NaN},
		"SO": {"value": NaN},
		"ZA": {"value": NaN},
		"GS": {"value": NaN},
		"SS": {"value": NaN},
		"ES": {"value": NaN},
		"LK": {"value": NaN},
		"SD": {"value": NaN},
		"SR": {"value": NaN},
		"SJ": {"value": NaN},
		"SE": {"value": NaN},
		"CH": {"value": NaN},
		"SY": {"value": NaN},
		"TW": {"value": NaN},
		"TJ": {"value": NaN},
		"TZ": {"value": NaN},
		"TH": {"value": NaN},
		"TL": {"value": NaN},
		"TG": {"value": NaN},
		"TK": {"value": NaN},
		"TO": {"value": NaN},
		"TT": {"value": NaN},
		"TN": {"value": NaN},
		"TR": {"value": NaN},
		"TM": {"value": NaN},
		"TC": {"value": NaN},
		"TV": {"value": NaN},
		"UG": {"value": NaN},
		"UA": {"value": NaN},
		"AE": {"value": NaN},
		"GB": {"value": NaN},
		"UM": {"value": NaN},
		"US": {"value": NaN},
		"UY": {"value": NaN},
		"UZ": {"value": NaN},
		"VU": {"value": NaN},
		"VE": {"value": NaN},
		"VN": {"value": NaN},
		"VG": {"value": NaN},
		"VI": {"value": NaN},
		"WF": {"value": NaN},
		"EH": {"value": NaN},
		"YE": {"value": NaN},
		"ZM": {"value": NaN},
		"ZW": {"value": NaN},
		"AX": {"value": NaN},
	}
	public countryListAlpha2 = {
		"AF": "Afghanistan",
		"AL": "Albania",
		"DZ": "Algeria",
		"AS": "AmericanSamoa",
		"AD": "Andorra",
		"AO": "Angola",
		"AI": "Anguilla",
		"AQ": "Antarctica",
		"AG": "AntiguaAndBarbuda",
		"AR": "Argentina",
		"AM": "Armenia",
		"AW": "Aruba",
		"AU": "Australia",
		"AT": "Austria",
		"AZ": "Azerbaijan",
		"BS": "Bahamas",
		"BH": "Bahrain",
		"BD": "Bangladesh",
		"BB": "Barbados",
		"BY": "Belarus",
		"BE": "Belgium",
		"BZ": "Belize",
		"BJ": "Benin",
		"BM": "Bermuda",
		"BT": "Bhutan",
		"BO": "Bolivia",
		"BQ": "Bonaire,SaintEustatiusAndSaba",
		"BA": "BosniaAndHerzegovina",
		"BW": "Botswana",
		"BV": "BouvetIsland",
		"BR": "Brazil",
		"IO": "BritishIndianOceanTerritory",
		"BN": "BruneiDarussalam",
		"BG": "Bulgaria",
		"BF": "BurkinaFaso",
		"BI": "Burundi",
		"CV": "CaboVerde",
		"KH": "Cambodia",
		"CM": "Cameroon",
		"CA": "Canada",
		"KY": "CaymanIslands",
		"CF": "CentralAfricanRepublic",
		"TD": "Chad",
		"CL": "Chile",
		"CN": "China",
		"CX": "ChristmasIsland",
		"CC": "CocosIslands",
		"CO": "Colombia",
		"KM": "Comoros",
		"CD": "Congo",
		"CG": "Congo",
		"CK": "CookIslands",
		"CR": "CostaRica",
		"HR": "Croatia",
		"CU": "Cuba",
		"CW": "Curaçao",
		"CY": "Cyprus",
		"CZ": "CzechRepublic",
		"CI": "Côted'Ivoire",
		"DK": "Denmark",
		"DJ": "Djibouti",
		"DM": "Dominica",
		"DO": "DominicanRepublic",
		"EC": "Ecuador",
		"EG": "Egypt",
		"SV": "ElSalvador",
		"GQ": "EquatorialGuinea",
		"ER": "Eritrea",
		"EE": "Estonia",
		"SZ": "Swaziland",
		"ET": "Ethiopia",
		"FK": "FalklandIslands",
		"FO": "FaroeIslands",
		"FJ": "Fiji",
		"FI": "Finland",
		"FR": "France",
		"GF": "FrenchGuiana",
		"PF": "FrenchPolynesia",
		"TF": "FrenchSouthernTerritories",
		"GA": "Gabon",
		"GM": "Gambia",
		"GE": "Georgia",
		"DE": "Germany",
		"GH": "Ghana",
		"GI": "Gibraltar",
		"GR": "Greece",
		"GL": "Greenland",
		"GD": "Grenada",
		"GP": "Guadeloupe",
		"GU": "Guam",
		"GT": "Guatemala",
		"GG": "Guernsey",
		"GN": "Guinea",
		"GW": "Guinea-Bissau",
		"GY": "Guyana",
		"HT": "Haiti",
		"HM": "HeardIslandAndMcdonaldIslands",
		"VA": "HolySee",
		"HN": "Honduras",
		"HK": "HongKong",
		"HU": "Hungary",
		"IS": "Iceland",
		"IN": "India",
		"ID": "Indonesia",
		"IR": "Iran",
		"IQ": "Iraq",
		"IE": "Ireland",
		"IM": "IsleOfMan",
		"IL": "Israel",
		"IT": "Italy",
		"JM": "Jamaica",
		"JP": "Japan",
		"JE": "Jersey",
		"JO": "Jordan",
		"KZ": "Kazakhstan",
		"KE": "Kenya",
		"KI": "Kiribati",
		"KP": "NorthKorea",
		"KR": "SouthKorea",
		"KW": "Kuwait",
		"KG": "Kyrgyzstan",
		"LA": "Laos",
		"LV": "Latvia",
		"LB": "Lebanon",
		"LS": "Lesotho",
		"LR": "Liberia",
		"LY": "Libya",
		"LI": "Liechtenstein",
		"LT": "Lithuania",
		"LU": "Luxembourg",
		"MO": "Macau",
		"MG": "Madagascar",
		"MW": "Malawi",
		"MY": "Malaysia",
		"MV": "Maldives",
		"ML": "Mali",
		"MT": "Malta",
		"MH": "MarshallIslands",
		"MQ": "Martinique",
		"MR": "Mauritania",
		"MU": "Mauritius",
		"YT": "Mayotte",
		"MX": "Mexico",
		"FM": "Micronesia",
		"MD": "Moldova",
		"MC": "Monaco",
		"MN": "Mongolia",
		"ME": "Montenegro",
		"MS": "Montserrat",
		"MA": "Morocco",
		"MZ": "Mozambique",
		"MM": "Myanmar",
		"NA": "Namibia",
		"NR": "Nauru",
		"NP": "Nepal",
		"NL": "Netherlands",
		"NC": "NewCaledonia",
		"NZ": "NewZealand",
		"NI": "Nicaragua",
		"NE": "Niger",
		"NG": "Nigeria",
		"NU": "Niue",
		"NF": "NorfolkIsland",
		"MP": "NorthernMarianaIslands",
		"NO": "Norway",
		"OM": "Oman",
		"PK": "Pakistan",
		"PW": "Palau",
		"PS": "Palestina",
		"PA": "Panama",
		"PG": "PapuaNewGuinea",
		"PY": "Paraguay",
		"PE": "Peru",
		"PH": "Philippines",
		"PN": "Pitcairn",
		"PL": "Poland",
		"PT": "Portugal",
		"PR": "PuertoRico",
		"QA": "Qatar",
		"MK": "Macedonia",
		"RO": "Romania",
		"RU": "Russia",
		"RW": "Rwanda",
		"RE": "Réunion",
		"BL": "SaintBarthélemy",
		"SH": "SaintHelena,AscensionandTristandaCunha",
		"KN": "SaintKittsAndNevis",
		"LC": "SaintLucia",
		"MF": "SaintMartin",
		"PM": "SaintPierreAndMiquelon",
		"VC": "SaintVincentAndTheGrenadines",
		"WS": "Samoa",
		"SM": "SanMarino",
		"ST": "SaoTomeAndPrincipe",
		"SA": "SaudiArabia",
		"SN": "Senegal",
		"RS": "Serbia",
		"SC": "Seychelles",
		"SL": "SierraLeone",
		"SG": "Singapore",
		"SX": "SintMaarten",
		"SK": "Slovakia",
		"SI": "Slovenia",
		"SB": "SolomonIslands",
		"SO": "Somalia",
		"ZA": "SouthAfrica",
		"GS": "SouthGeorgiaandtheSouthSandwichIsla",
		"SS": "SouthSudan",
		"ES": "Spain",
		"LK": "SriLanka",
		"SD": "Sudan",
		"SR": "Suriname",
		"SJ": "SvalbardAndJanMayen",
		"SE": "Sweden",
		"CH": "Switzerland",
		"SY": "Syria",
		"TW": "Taiwan",
		"TJ": "Tajikistan",
		"TZ": "Tanzania",
		"TH": "Thailand",
		"TL": "TimorLeste",
		"TG": "Togo",
		"TK": "Tokelau",
		"TO": "Tonga",
		"TT": "TrinidadAndTobago",
		"TN": "Tunisia",
		"TR": "Turkey",
		"TM": "Turkmenistan",
		"TC": "TurksandCaicasIslands",
		"TV": "Tuvalu",
		"UG": "Uganda",
		"UA": "Ukraine",
		"AE": "UnitedArabEmirates",
		"GB": "UnitedKingdom",
		"UM": "UnitedStatesMinorOutlyingIslands",
		"US": "UnitedStates",
		"UY": "Uruguay",
		"UZ": "Uzbekistan",
		"VU": "Vanuatu",
		"VE": "Venezuela",
		"VN": "Vietnam",
		"VG": "BritishVirginIslands",
		"VI": "VirginIslands",
		"WF": "Wallis and Futuna",
		"EH": "WesternSahara",
		"YE": "Yemen",
		"ZM": "Zambia",
		"ZW": "Zimbabwe",
		"AX": "Åland"
	};
}
