version: '3.4'

services:
  frontend:
    container_name: habitablEarth-frontend
    build:
      context: .
      dockerfile: ./habitablEarth/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    environment:
      - NGINX_HOST=habitable-earth.eu
    networks:
      - habitablEarth-network
    depends_on:
      - backend
  backend:
    container_name: habitablEarth-backend
    build: ./backend
    volumes:
      - ./:/backend/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
    networks:
      - habitablEarth-network
  certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw
    

networks:
  habitablEarth-network:
    driver: bridge