name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    environment: production
    concurrency: production
    steps:
      - name: Install dependencies
        run: |
          sudo yum update -y
          sudo yum install -y sshpass

      - name: Deploy to VM
        run: |
          sshpass -p ${{ secrets.SSH_PRIVATE_KEY }} ssh ${{ secrets.ACC }} 'cd /habitablEarth && git pull origin main && docker-compose restart'
          
      
